### PR TITLE
Slightly nice comic image

### PR DESCRIPTION
**Pull request by thejohnhoffer**
I'd like to call the main character `Earnest` and the comic itself `L'earnest`. Earnest always gives the most technical explanations possible instead of easier wordings. The name of the comic `Le (the) + Earnest`is close to the word "learnedest", which yes, [was once used as a word][0]. Plus, __L'earnest__ fits with our blog name "The Learn Blog"

A machine learning researcher in the wild

[0]: https://books.google.com/ngrams/graph?content=learnedest&year_start=1800&corpus=15&smoothing=0

### CODE REVIEW

**Comment by ironman5366** [comment]
Awesome!

**Comment by thejohnhoffer** [comment]
Note: There first two commits cancel eachother out. The third commit just changes one line in `_posts/2017-02-26-Lesson01-Neurons.md` I initially wanted to host the images here, but then I didn't really want to figure out how to host with jekyll, so I'm hosting them at `img.hoff.in`, which is my own github repository.

**Comment by thejohnhoffer** [comment]
I'll just go ahead and merge these then. 👍

**Comment by ironman5366** [comment]
@thejohnhoffer Yeah, sorry, I tried to but I couldn't figure out how on mobile. Thanks!

**Pull request merged**
